---
title: tahull
description: > # this means to ignore newlines until "baseurl:"
  Electronics, PCB's, projects with PIC microcontrollers, and linux stuff
baseurl: ""
url: "https://tahull.github.io"
repository: tahull/tahull.github.io
#github_username:
#excerpt_separator: "<!--more-->"

# Custom
current_version:      0.1.20

# Build settings
markdown: kramdown
highlighter: rouge

#google analytics
google_analytics: UA-122054232-1

#comments
disqus:
  shortname: tahull

paginate: 5

plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from



# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
